name: Ecclesia CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # checkout
      - uses: actions/checkout@v2

      # checkout ecclesia actions
      - uses: actions/checkout@v2
        name: Checkout ecclesia/workflows
        with:
          path: ".ecclesia"
          repository: ecclesia/workflows
          token: ${{ secrets.GHCR_TOKEN }}

      # prepare Buildenvironment
      - uses: ./.ecclesia/.ecclesia-actions/prepare-environment
        name: Prepare Ecclesia Buildenvironment
        with:
          checkout_path: ".ecclesia"
          ghcr_token: ${{secrets.GHCR_TOKEN}}
          maven_add_bintray_repo: "true"
          use_maven_cache: "true"
